version: "3.1"
services:

  nginx:
    image: tutum/nginx
    ports:
      - "80:80"
    links:
      - php-fpm
    volumes:
      - ./nginx/default:/etc/nginx/sites-available/default
      - ./nginx/default:/etc/nginx/sites-enabled/default

      - ./logs/nginx-access.log:/var/log/nginx/access.log
      - ./logs/nginx-error.log:/var/log/nginx/error.log

  php-fpm:
    build:
      context: .
      dockerfile: ./php-fpm/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./application:/application
    depends_on:
      - mysql
    environment:
      WAIT_HOSTS: rabbit1:5672, nginx:80

  mysql:
    image: mysql:5.7
    # volumes:
    #   - ./var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=forge
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    ports:
      - "3306:3306"

  rabbit1:
    image: "rabbitmq:3-management"
    hostname: "rabbit1"
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    labels:
      NAME: "rabbitmq1"
#    volumes:
#      - "./enabled_plugins:/etc/rabbitmq/enabled_plugins"
      #- "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro"
      #- "./autocluster-0.4.1.ez:/usr/lib/rabbitmq/lib/rabbitmq_server-3.5.5/plugins/autocluster-0.4.1.ez"